name: CI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - id: buildx
        name: Setup
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        run: |
          docker buildx build --no-cache --push \
            --platform ${{ steps.buildx.outputs.platforms }} \
            --tag ghcr.io/${{ github.actor }}/pod-gateway:dev-latest \
            --tag ghcr.io/${{ github.actor }}/pod-gateway:dev-$(echo $GITHUB_SHA | head -c7) \
            .
